runtime: java8
env: flex

env_variables:
  SPRING_DATASOURCE_URL: jdbc:mysql://google/economia_circular?cloudSqlInstance=economia-circular-470222:us-central1:mi-instancia-sql&socketFactory=com.google.cloud.sql.mysql.SocketFactory
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: PirAta.22

beta_settings:
  cloud_sql_instances: economia-circular-470222:us-central1:mi-instancia-sql

handlers:
  - url: /.*
    script: auto
