-- =====================================================
-- Seed inicial de políticas y reglas de la plataforma
-- Solo se ejecuta en contexto prod
-- =====================================================

INSERT INTO politicas (tipo, titulo, contenido, activo, orden, creado_en, actualizado_en) VALUES (
  'TERMINOS_USO',
  'Términos y Condiciones de Uso',
  '## Términos y Condiciones de Uso\n\n**Última actualización:** enero de 2025\n\n### 1. Aceptación de los términos\n\nAl registrarte y utilizar Economía Circular, aceptás estos términos en su totalidad. Si no estás de acuerdo con alguna parte, no deberías usar la plataforma.\n\n### 2. Descripción del servicio\n\nEconomía Circular es una plataforma digital que facilita el intercambio, donación y venta de artículos entre usuarios, con el objetivo de reducir el desperdicio y promover el consumo responsable.\n\n### 3. Registro y cuenta\n\n- Debés proporcionar información veraz al registrarte.\n- Sos responsable de mantener la confidencialidad de tu contraseña.\n- Una persona solo puede tener una cuenta activa.\n- Nos reservamos el derecho de suspender cuentas que incumplan estos términos.\n\n### 4. Publicación de artículos\n\n- Los artículos publicados deben ser de tu propiedad.\n- No se permite publicar artículos ilegales, peligrosos, falsificados o que infrinjan derechos de terceros.\n- Las descripciones deben ser honestas y precisas.\n- Nos reservamos el derecho de remover publicaciones que incumplan las reglas.\n\n### 5. Intercambios y transacciones\n\nLa plataforma actúa como intermediario de contacto. Las transacciones finales son responsabilidad exclusiva de los usuarios. Economía Circular no garantiza el resultado de ningún intercambio ni asume responsabilidad por disputas entre usuarios.\n\n### 6. Limitación de responsabilidad\n\nEconomía Circular no será responsable por daños directos, indirectos, incidentales o consecuentes derivados del uso de la plataforma.\n\n### 7. Modificaciones\n\nPodemos actualizar estos términos. Te notificaremos ante cambios significativos. El uso continuado de la plataforma implica la aceptación de los nuevos términos.',
  1, 1, NOW(), NOW()
);

INSERT INTO politicas (tipo, titulo, contenido, activo, orden, creado_en, actualizado_en) VALUES (
  'POLITICA_PRIVACIDAD',
  'Política de Privacidad',
  '## Política de Privacidad\n\n**Última actualización:** enero de 2025\n\n### 1. Información que recopilamos\n\n**Datos que nos proporcionás:**\n- Nombre y apellido\n- Dirección de correo electrónico\n- Domicilio (opcional)\n- Foto de perfil (opcional)\n- Artículos publicados y sus imágenes\n\n**Datos generados por el uso:**\n- Historial de intercambios y solicitudes\n- Valoraciones recibidas y emitidas\n- Mensajes enviados dentro de la plataforma\n- Fecha de registro y actividad\n\n### 2. Cómo usamos tu información\n\n- Para gestionar tu cuenta y permitirte usar la plataforma.\n- Para enviar notificaciones sobre actividad relevante (nuevos mensajes, solicitudes, etc.).\n- Para enviarte emails transaccionales (verificación, recuperación de contraseña).\n- Para generar estadísticas anónimas de uso de la plataforma.\n\n### 3. Compartir información\n\n**No vendemos ni cedemos tus datos personales a terceros.** Tu nombre y foto de perfil son visibles para otros usuarios dentro de la plataforma. Tu email nunca es compartido públicamente.\n\n### 4. Seguridad\n\nTus contraseñas se almacenan cifradas mediante BCrypt. Utilizamos JWT con expiración para las sesiones. Las conexiones son protegidas por HTTPS.\n\n### 5. Tus derechos\n\nPodés solicitar en cualquier momento:\n- Acceso a tus datos personales\n- Corrección de datos incorrectos\n- Eliminación de tu cuenta y datos asociados\n\nPara ejercer estos derechos, contactanos a través del chat de soporte.\n\n### 6. Retención de datos\n\nConservamos tus datos mientras tu cuenta esté activa. Al eliminar tu cuenta, los datos personales son anonimizados dentro de los 30 días siguientes.',
  1, 2, NOW(), NOW()
);

INSERT INTO politicas (tipo, titulo, contenido, activo, orden, creado_en, actualizado_en) VALUES (
  'REGLAS_COMUNIDAD',
  'Reglas de la Comunidad',
  '## Reglas de la Comunidad\n\nEconomía Circular es un espacio de confianza. Para que funcione bien para todos, pedimos que respetes estas reglas.\n\n### Lo que SÍ podés hacer\n\n- Publicar artículos en buen estado que ya no uses.\n- Proponer intercambios honestos y cumplir con lo acordado.\n- Valorar a otros usuarios después de completar un intercambio.\n- Usar el chat de soporte si tenés un problema.\n- Reportar publicaciones o usuarios que incumplan las reglas.\n\n### Lo que NO está permitido\n\n**Artículos prohibidos:**\n- Armas, municiones o artículos peligrosos.\n- Medicamentos, drogas o sustancias controladas.\n- Productos falsificados o que infrinjan derechos de autor.\n- Artículos robados o de procedencia dudosa.\n- Animales vivos.\n\n**Comportamiento prohibido:**\n- Publicar información falsa o engañosa en los artículos.\n- Usar la plataforma para spam o publicidad no autorizada.\n- Acosar, insultar o discriminar a otros usuarios.\n- Crear múltiples cuentas para evadir suspensiones.\n- Manipular el sistema de valoraciones.\n\n### Condición de los artículos\n\nSea honesto al describir el estado de tus artículos:\n- **Nuevo:** sin uso, en su embalaje original.\n- **Usado:** con uso normal, en buen estado de funcionamiento.\n- **Reacondicionado:** fue reparado o restaurado.\n- **Averiado:** tiene fallas, se publica para repuestos o reparación.\n\n### Consecuencias del incumplimiento\n\nEl incumplimiento de estas reglas puede resultar en la eliminación de publicaciones, suspensión temporal o baja permanente de la cuenta, según la gravedad de la infracción.',
  1, 3, NOW(), NOW()
);

INSERT INTO politicas (tipo, titulo, contenido, activo, orden, creado_en, actualizado_en) VALUES (
  'FAQ',
  'Preguntas Frecuentes',
  '## Preguntas Frecuentes\n\n### ¿Cómo publico un artículo?\n\nIniciá sesión, hacé clic en "Publicar artículo" y completá el formulario con título, descripción, categoría, condición y fotos. Podés agregar hasta 5 imágenes.\n\n### ¿Cómo funciona el intercambio?\n\nCuando encontrás un artículo que te interesa, hacés una solicitud ofreciendo uno de tus artículos a cambio. El propietario del artículo puede aceptar, rechazar o ignorar la solicitud. Si acepta, coordináis los detalles por el chat de mensajes.\n\n### ¿Es gratis usar la plataforma?\n\nSí, Economía Circular es completamente gratuita. No cobramos comisiones por los intercambios.\n\n### ¿Cómo me registro?\n\nHacé clic en "Registrarse", completá tus datos y verificá tu email haciendo clic en el enlace que te enviamos. Después podés iniciar sesión.\n\n### ¿Olvidé mi contraseña, qué hago?\n\nEn la pantalla de login, hacé clic en "¿Olvidaste tu contraseña?", ingresá tu email y te enviaremos un enlace para crear una nueva contraseña. El enlace es válido por 60 minutos.\n\n### ¿Puedo eliminar un artículo publicado?\n\nSí, desde tu perfil podés cancelar cualquier publicación que no tenga intercambios en curso.\n\n### ¿Cómo se calcula la reputación?\n\nOtros usuarios pueden valorarte del 1 al 5 luego de completar un intercambio. Tu perfil muestra el promedio de todas las valoraciones recibidas.\n\n### ¿Qué hago si tengo un problema con otro usuario?\n\nUsá el chat de soporte para contactar al equipo de administración. Describiremos el problema y lo resolveremos a la brevedad.',
  1, 4, NOW(), NOW()
);
